# Site Settings

title: VibhMitra
email: vibhanshumitra@gmail.com
author: Vibhanshu Mitra
description: >
  This is my github page.
baseurl: ""
url: ""
github_username: vibhmitra


# Build Settings
# theme: jekyll-theme-minimal
theme: minima
